version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_USER:-postgres}
      GOGS_DATABASE: ${GOGS_DB:-gogs}
      GOGS_USER: ${GOGS_DB_USER:-gogs}
      GOGS_PASSWORD: ${GOGS_DB_PASS:-gogs}
    volumes:
       - pg_data:/var/lib/postgresql/data
       - ./conf/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"
    restart: unless-stopped
  gogs:
    container_name: gogs
    image: gogs/gogs
    ports:
      - ${GOGS_PORT:-3000}:3000
    volumes:
      - gogs_data:/data
      - gogs_backup:/backup
      - ./conf/app.ini:/data/gogs/conf/app.ini:ro
    environment:
      - TZ=Asia/Shanghai
    restart: always
    depends_on:
      - db

volumes:
  pg_data:
  gogs_data:
  gogs_backup:
