version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    user: 501:20
    environment:
      POSTGRES_USER: nextchen
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gogs
    volumes:
       - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  gogs:
    container_name: gogs
    image: gogs/gogs
    ports:
      - ${GOGS_PORT:-3000}:3000
    volumes:
      - ./data/gogs:/data
      - ./data/gogs_bakcup:/backup
      - ./conf/app.ini:/data/gogs/conf/app.ini:ro
    environment:
      - TZ=Asia/Shanghai
    restart: always
    depends_on:
      - db
