version: '3.8'
services:
  drone-agent:
    image: drone/drone-runner-docker:1-linux-arm64
    container_name: drone-agent
    ports:
      - 3001:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=d295982b36f2cfbc1fd657e476d2e846
      - DRONE_RUNNER_CAPACITY=${DRONE_RUNNER_CAPACITY:-1}
      - DRONE_RUNNER_NAME=my-first-runner
      - DRONE_DEBUG=true
      - DRONE_TRACE=true
      - DRONE_RPC_DUMP_HTTP=true
      - DRONE_RPC_DUMP_HTTP_BODY=true
      - DRONE_HTTP_BIND=:3001
      - DRONE_UI_USERNAME=root
      - DRONE_UI_PASSWORD=root
      - DRONE_RUNNER_NETWORKS=deployment-service_default
      - TZ=Asia/Shanghai
    restart: always

networks:
  default:
    name: deployment-service_default
    external: true

