version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_USER:-postgres}
      GOGS_DATABASE: ${GOGS_DB:-gogs}
      GOGS_USER: ${GOGS_DB_USER:-gogs}
      GOGS_PASSWORD: ${GOGS_DB_PASS:-gogs}
      DRONE_DATABASE: ${DRONE_DB:-drone}
      DRONE_USER: ${DRONE_DB_USER:-drone}
      DRONE_PASSWORD: ${DRONE_DB_PASS:-drone}
    volumes:
       - pg_data:/var/lib/postgresql/data
       - ./conf/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"
    restart: unless-stopped
  db-admin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: echenwen@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  gogs:
    container_name: gogs
    image: gogs/gogs
    ports:
      - ${GOGS_PORT:-3000}:3000
    volumes:
      - gogs_data:/data
      - gogs_backup:/backup
      - ./conf/app.ini:/data/gogs/conf/app.ini:ro
    environment:
      - TZ=Asia/Shanghai
    restart: always
    depends_on:
      - db

  drone-server:
    image: drone/drone:2-linux-arm64
    container_name: drone-server
    ports:
      - 80:80
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - drone_lib:/var/lib/drone
      - drone_data:/data
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_USER_CREATE=username:${DRONE_ADMIN:-gogs},admin:true
      - DRONE_SERVER_PROTO=http
      - DRONE_SERVER_HOST=drone-server
      - DRONE_RPC_SECRET=d295982b36f2cfbc1fd657e476d2e846
      - DRONE_GOGS_SERVER=http://gogs:3000
      - DRONE_DATABASE_DRIVER=postgres
      - DRONE_DATABASE_DATASOURCE=postgres://${DRONE_DB_USER:-drone}:${DRONE_DB_PASS:-drone}@db:5432/${DRONE_DB:-drone}?sslmode=disable
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TRACE=true
      - DRONE_LOGS_TEXT=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true
      # - DRONE_GOGS_SKIP_VERIFY=false
      - TZ=Asia/Shanghai
    restart: always
    depends_on:
      - db
  drone-agent:
    image: drone/drone-runner-docker:1-linux-arm64
    container_name: drone-agent
    depends_on:
      - drone-server
    ports:
      - 3001:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_SECRET=d295982b36f2cfbc1fd657e476d2e846
      - DRONE_RUNNER_CAPACITY=${DRONE_RUNNER_CAPACITY:-1}
      - DRONE_RUNNER_NAME=my-first-runner
      - DRONE_RUNNER_NETWORKS=deployment-service_default
      - DRONE_DEBUG=true
      - DRONE_TRACE=true
      - DRONE_RPC_DUMP_HTTP=true
      - DRONE_RPC_DUMP_HTTP_BODY=true
      - DRONE_HTTP_BIND=:3001
      - DRONE_UI_USERNAME=root
      - DRONE_UI_PASSWORD=root
      - TZ=Asia/Shanghai
    restart: always

volumes:
  pg_data:
  pgadmin-data:
  gogs_data:
  gogs_backup:
  drone_lib:
  drone_data:
