version: '3'
services:
  drone-docker-agent:
    image: drone/drone-runner-docker:1-linux-arm64
    container_name: drone-agent
    ports:
      - ${AGENT_PORT:-3000}:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_HOST=${DRONE_SERVER_HOST:-drone-server}
      - DRONE_RPC_SECRET=${DRONE_SERVER_SECRET:-d295982b36f2cfbc1fd657e476d2e846}
      - DRONE_RUNNER_CAPACITY=${DRONE_RUNNER_CAPACITY:-1}
      - DRONE_RUNNER_NAME=${DRONE_RUNNER_NAME:-my-runner}
      - DRONE_DEBUG=true
      - DRONE_TRACE=true
      - DRONE_RPC_DUMP_HTTP=true
      - DRONE_RPC_DUMP_HTTP_BODY=true
      - TZ=Asia/Shanghai
    restart: always
