#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $GOGS_USER WITH PASSWORD '${GOGS_PASSWORD}';
    CREATE DATABASE $GOGS_DATABASE owner=$GOGS_USER;
    CREATE USER $DRONE_USER WITH PASSWORD '${DRONE_PASSWORD}';
    CREATE DATABASE $DRONE_DATABASE owner=$DRONE_USER;
EOSQL
