version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:

services:
  grafana:
    image: grafana/grafana-oss:9.4.7
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    networks:
      - monitoring
