global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: 
        - 'host.internal:9100'
        - '10.0.0.80:9100'
        - '10.0.0.79:9100'
        - '10.0.0.86:9100'
